version: 2
jobs:
  build:
    name: Run Spectral
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Setup Test Dir
          command: mkdir ~/junit
      - run:
          name: "API Description Linter"
          command: npx @stoplight/spectral@6.0.0-alpha3 lint reference/*.yml -f=junit -o ~/junit/test_results.xml -v -F=error --ruleset=./.spectral.yaml
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
